# -*- coding: utf-8 -*-
"""Essential Python for DA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTj8hsvG2wiN0Sbr5zQ4-IstrGff3kcU

# Essential Python for DA
- Object Oriented programming
- Read and Write file
- Context Manager
- Handle Error
- Pandas & Numpy(on demand)
- Request API

OOP
- is what we teach computer learn
- concept is like cookie cooker
- pum cookie cooker is class in python
"""

class Dog:
  pass

dog1 = Dog()
dog2 = Dog()

dog2

class Dog:
  def __init__(self, name, species,age):
    self.name = name
    self.species = species
    self.age = age

  def bark(self):
    print(f"{self.name} is barking 'hong hong'!")

  def hbd(self):
    self.age += 1

dog1 = Dog("milo", "chiwawa",2)
dog2 = Dog("david", "Husky",3)

dog1.name

print(f"{dog1.name} is {dog1.species}")

print(f"{dog2.name} is {dog2.species}")

dog1.bark()

print(dog1.age)
dog1.hbd()
print(dog1.age)



"""## OOP

* attributes:name, species, age
* method:function bark() hbd()
"""

#home work OOP for ATM

##deposit,withdraw,check balance, OTP,order coffee, pay bill, internet , etc

class ATM:
  def __init__(self, username, bank_name,amount):
    self.username = username
    self.bank = bank_name
    self.amount = amount

  def __str__(self):   ##return string
    return f"{self.username} uses {self.bank} and has {self.amount} THB in an account"

  def check_balance(self):
    print(f"Blance: {self.amount} THB")

  def deposit(self, saving):
    self.amount += saving
    print(f"Deposit {saving} THB successfully!")

may = ATM("saruda may","ttb",100)

print(f"{may.username} opens a new bank account at {may.bank}")

may.check_balance()

may.deposit(200)

print(may)

"""# Super class

"""

##base software

class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

##extension / add feature
class Employee(Person):
  def __init__(self,name,age,company):
    super().__init__(name,age)
    self.company = company
  def greeting(self):
    print("Hello World!")

may = Person("may",39)

may.name, may.age

person1= Person("may",39)

person2 = Employee("lisa",28,"google")



"""Try Except Block"""

try:
  result = 1/0

except:
  print("this is an error message!")

"""# Read & Write Files"""

!ls

!cat hotel.csv

##read file
import csv

try:

  file = open("hotel.csv","r") # r=read,w=write,a=append

#csv.reader()
  data = csv.reader(file)

  for row in data:
    print(row)

  file.close()

except FileNotFoundError:
  print("file not found, please check filename again.")

finally:
  print("read file successfully")

#contex manager
read_data = []

with open("hotel.csv","r") as file:
  data = csv.reader(file)
  for row in data:
    read_data.append(row)

read_data

fruits = ["orange","banana","mango"]
fruits.append("durian")

print(fruits)

##R
#mean(data$price_per_night)
##python no average
## for loop to calculate avg. price per night

prices = []

for row in read_data[1: ]:
  prices.append(int(row[4])) ##-1 the last item

print(f"Average price per night: {sum(prices)/ len(prices)}")

#modern python
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

df.price_per_night.mean()

df["price_per_night"].mean()

#write file + context manager
#native python
head = ["id","name","city"]
body = [
    [1, "CU","Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]


]


with open("school.csv","w") as file:
  writer = csv.writer(file)
  writer.writerow(head)
  writer.writerows(body) # body data more than 1 row

!ls

!cat school.csv

#modern python
import pandas as pd

df=pd.read_csv("school.csv")

df.head()

df.to_csv("school2.csv")

!ls

!cat school2.csv

##read data from internet
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

import pandas as pd
df_penguin = pd.read_csv(url)

df_penguin.tail()

df_penguin.head()

import pandas as pd
from pandas import read_csv
df_penguin = read_csv

## select column
df_penguin[["species","island","body_mass_g"]].head(10)

#filter rows
df_penguin[["species","island","body_mass_g"]].query("species == 'Adelie' and island == 'Dream'")

##filter without query()
df_penguin[df_penguin['body_mass_g']>=4500][["species","sex","body_mass_g"]]

"""# Requests

How to get data via API the easy way
"""

##request api

import requests

##api endpoint

url = "https://swapi.info/api/people/1"

response = requests.get(url)
##success response 200

response.json()["name"]

response.json()["height"]

##for loop

for i in range (10):
  print(i+1)  ##python start with 0

##for loop
import requests
import time

characters =[]

for i in range(10):
  url= f"https://swapi.info/api/people/{i+1}"
  response = requests.get(url)
  response_json = response.json()
  data = [response_json["name"],
          response_json["height"],
          response_json["mass"]]
  characters.append(data)
  print(f"success: {i+1}")
  time.sleep(1)

print(characters)

#create dataframe from list
import pandas as pd

starwars = pd.DataFrame(characters, columns = ["name","height","mass"])

starwars

