# -*- coding: utf-8 -*-
"""On demand Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJnvY3ToDUnn08yiUe1DB7QKiLCPLqfE
"""

import requests

url = "https://swapi.info/api/people/1"

response = requests.get(url)

response.json()["name"]

response.json()["height"]

response.json()["mass"]

##for loop
import requests
import time
name = []
for i in range(10):
  url = f"https://swapi.info/api/"people/{i+1}"
  response = request.get(url)
  response_json = response.json()

  names.append(response_json["name"])
  time.sleep(1)

import pandas as pd

from google.colab import files


uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['penguins.csv']))
print(df)

penguins = pd.read_csv("penguins.csv")

#preview first 5 rows
penguins.head()

#preview last 5 rows
penguins.tail()

penguins.shape

#information of dataframe
penguins.info()

#select columns
penguins.species

penguins[['species','island','sex']].tail(8)

#integer location based indexing (iloc)
penguins.iloc[0:3]

penguins.iloc[0:5, [0,1,2]]

#deposit function
mini_penguins = penguins.iloc[0:5,0:3]
mini_penguins

#filter rows by a condition
penguins['island'] =='Torgersen'  ## boulean in True, False

#filter rows by a condition
#transfer boulean to datafram to filter data
penguins [penguins['island'] =='Torgersen']  ## boulean in True, False

penguins [penguins['bill_length_mm'] <34]

#filter more than one condition
penguins [(penguins['island'] == 'Torgersen') & (penguins['bill_length_mm']<35)]

penguins [(penguins['island'] == 'Torgersen') | (penguins['bill_length_mm']<35)]

filtered_penguins = penguins [(penguins['island'] == 'Torgersen') | (penguins['bill_length_mm']<35)]

#filter with query()
penguins.query('island == "Torgersen" & bill_length_mm < 35') #"island == 'Torgersen'"

#check missing in each column
penguins.isna().sum()  #if na = true

#filter missing values in column sex
penguins[ penguins['sex'].isna()]

#drop na
clean_penguins = penguins.dropna()
clean_penguins.head(10)

#fill missing values
#deposit function first
top5_penguins =penguins.head(5)

avg_value = top5_penguins ['bill_length_mm'].mean()
print(avg_value)

top5_penguins = top5_penguins['bill_length_mm'].fillna(value = avg_value )
top5_penguins

#sort bill_length_mm low to high, high to low
penguins.dropna().sort_values('bill_length_mm',ascending=False).head(10)

#sort multiple columns
penguins.dropna().sort_values(['island','bill_length_mm'])

#unique values
penguins['species'].unique()

#count values
penguins['species'].value_counts()

#rename column or frequency table.
result = penguins[['island','species']].value_counts().reset_index()
result.columns = ['island','species','count']
result

#summarise dataframe
penguins.head()

#average, mean
penguins['bill_length_mm'].median()

#groupby + sum/mean
penguins[penguins['species'] == 'Adelie']['bill_length_mm'].mean()
penguins[penguins['species'] == 'Adelie']['bill_length_mm'].mean()

#dataframe name + group by method + by category + column need to calculate + function
penguins.groupby('species')['bill_length_mm'].mean()

#aggregation multiple
penguins.groupby('species')['bill_length_mm'].agg(['min','mean','median','std','max'])

#group by more than one columns
penguins.groupby(['island','species'])['bill_length_mm'] \
  .agg(['min','mean','max']) \
  .reset_index()

#map value MALE: m, FEMALE: f
penguins['sex_new'] = penguins['sex'].map({'MALE':'m','FEMALE':'f'}).fillna('other')
penguins.head()

#pandas style
penguins['bill_length_mm'].mean()

#numpy
import numpy as np
np.mean(penguins['bill_length_mm'])

#other functions of numpy
print(np.sum(penguins['bill_depth_mm']))
print(np.std(penguins['body_mass_g']))

score = pd.Series([80,55,62,95,20])

grade = np.where(score >= 80, "passed","failed")
print(grade)

penguins.query("species == 'Adelie' ")[['species','island','bill_length_mm']].dropna()

df['new_column'] = np.where(df['bill_length_mm']>40,True,False) #boolean

df.head(10)

#pandas dictionary dataframe
left = {
    'key':[1,2,3,4],
    'name':['toy','joe','jane','anna'],
    'age':[25,28,30,22]

}
right = {
    'key':[1,2,3,4],
    'city':['Bangkok','London','Seoul','Tokyo'],
    'zip': [1001,2504,2094,9802]

}
df_left=pd.DataFrame(left)
df_right=pd.DataFrame(right)

df_left

import pandas as pd
df_result = pd.merge(df_left,df_right,on='key')
df_result

#histogram one column
penguins['body_mass_g'].plot(kind='hist');

penguins[['body_mass_g','bill_length_mm']].plot(kind='hist',bins=30)

penguins['bill_length_mm'].plot(kind='hist',bins=30,color ="orange");

#bar plot for species
penguins['species'].value_counts().plot(kind='bar',color=['salmon','orange','gold'])

#scatter plot
penguins[['bill_length_mm','bill_depth_mm']] \
.plot(x='bill_length_mm', y='bill_depth_mm',kind="scatter",color="orange")

penguins





from matplotlib import pyplot as plt
penguins.plot(kind='scatter', x='flipper_length_mm', y='body_mass_g', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

